
window.visualizarSolicitacaoMovimentacao = visualizarSolicitacaoMovimentacao;
window.editarSolicitacaoMovimentacao = editarSolicitacaoMovimentacao;
window.preencherVagaMovimentacao = preencherVagaMovimentacao;
window.excluirSolicitacaoMovimentacao = excluirSolicitacaoMovimentacao;
